name: Build Tailwind CSS

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      # 🔥 install tailwind + CLI fix
      - run: npm install -D tailwindcss@3.4.3

      # 🔥 build pakai npx (akan jalan)
      - run: npx tailwindcss -i ./input.css -o ./static/css/style.css --minify

      - name: Commit CSS
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add static/css/style.css
          git commit -m "auto build css" || echo "no changes"
          git push
